services:
  - type: web
    name: donation-platform
    runtime: docker
    plan: starter
    healthCheckPath: /

    envVars:
      - key: APP_NAME
        value: Donation

      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: APP_KEY
        sync: false

      - key: APP_URL
        scope: self
        value: https://${RENDER_EXTERNAL_HOSTNAME}

      - key: LOG_CHANNEL
        value: stderr

      - key: LOG_LEVEL
        value: info

      - key: CACHE_DRIVER
        value: file

      - key: SESSION_DRIVER
        value: file

      - key: QUEUE_CONNECTION
        value: sync

      - key: FILESYSTEM_DISK
        value: public

      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        fromDatabase:
          name: donation-mysql
          property: host

      - key: DB_PORT
        fromDatabase:
          name: donation-mysql
          property: port

      - key: DB_DATABASE
        fromDatabase:
          name: donation-mysql
          property: database

      - key: DB_USERNAME
        fromDatabase:
          name: donation-mysql
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: donation-mysql
          property: password

databases:
  - name: donation-mysql
    plan: starter
    databaseName: donations
    user: donations
